web_server_make: web_server.c
	gcc  web_server.c read_file.c logger.c -o ../build/read 
	@echo "###############################"
	@../build/read 6060
	@echo "###############################"
	@rm read